
name: generate-docs

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: python3 --version
        run: python3 --version
        
      - name: pip3 install rdflib
        run: pip3 install rdflib
        
      - name: python3 generate-docs.py
        run: python3 generate-docs.py
      
      - name: commit html files
        run: |
          git config --global user.name "Robert Brook"
          git config --global user.email robertbrook@fastmail.fm
          git add "doctest.html"
          git commit -am "Added html files."
          git push
          
