
name: generate-docs

on:
  push:
    branches: 
      - master

  workflow_dispatch:

jobs:

  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: pip3 install rdflib
        run: pip3 install rdflib

      - name: pip3 install Jinja2
        run: pip3 install Jinja2
        
      - name: python3 meta/generate-docs.py
        run: python3 meta/generate-docs.py
        
      - name: python3 meta/generate-docs-index.py
        run: python3 meta/generate-docs-index.py
        


          
