
name: generate-docs

on:
  push:
    branches: 
      - master

  workflow_dispatch:

jobs:

  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        
      - name: pip3 install rdflib
        run: pip3 install rdflib
        
      - name: python3 generate-docs.py
        run: python3 generate-docs.py
      
      - name: commit html files
        run: |
          git config --global user.name "Robert Brook"
          git config --global user.email "robertbrook@fastmail.fm"
          git commit -am "Added html files."
          git push

      - name: github event
        run: echo echo "${{ github.event.commits.added }}"
          
