
name: p-generate-docs

on:
  push:
    branches: 
      - master

  workflow_dispatch:

jobs:

  generate:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2

      - name: curl -L https://github.com/janet-lang/janet/archive/refs/heads/master.zip --output janet.zip
        run: curl -L https://github.com/janet-lang/janet/archive/refs/heads/master.zip --output janet.zip
        
      - name: unzip, cd, make
        run: unzip janet.zip; cd janet-master; make; make test; make repl

      - name: cd, janet -v
        run: cd; janet -v



          
