
name: p-generate-docs

on:
  push:
    branches: 
      - master

  workflow_dispatch:

jobs:

  generate:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2
      
      - name: add prolog ppa
        run: sudo add-apt-repository ppa:swi-prolog/stable

      - name: update
        run: sudo apt-get update
        
      - name: install prolog
        run: sudo apt-get install swi-prolog

      - name: show prolog version
        run: swipl --version



          
