
name: p-generate-docs

on:
  push:
    branches: 
      - master

  workflow_dispatch:

jobs:

  generate:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2
      - name: perlbrew install-cpanm
        run: perlbrew install-cpanm
        
      - name: cpanm install Attean
        run: cpanm install Attean


        


          
