
name: p-generate-docs

on:
  push:
    branches: 
      - master

  workflow_dispatch:

jobs:

  generate:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2


      - name: curl -L https://github.com/janet-lang/janet/archive/refs/heads/master.zip --output janet.zip
        run: curl -L https://github.com/janet-lang/janet/archive/refs/heads/master.zip --output janet.zip
        
      - name: unzip janet.zip
        run: unzip janet.zip

      - name: cd janet-master
        run: cd janet-master
        
      - name: ls
        run: ls
        
      - name: make
        run: make


          
