
name: p-generate-docs

on:
  push:
    branches: 
      - master

  workflow_dispatch:

jobs:

  generate:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v2

        
      - name: perl -MCPAN -e 'install Attean'
        run: perl -MCPAN -e 'install Attean'


        


          
